stages:
  data_ingestion:
    cmd: python3 src/dlProject/components/data_ingest.py
    deps:
      - src/dlProject/components/data_ingest.py
      - config/config.yaml
    outs:
      - artifacts/data_feb16/data_ingestion

  data_transformation:
    cmd: python3 src/dlProject/components/data_transform.py
    deps:
      - src/dlProject/components/data_transform.py
      - artifacts/data_feb16/data_ingestion
      - config/config.yaml
    outs:
      - artifacts/data_feb16/data_transformation  

  data_split:
    cmd: python3 src/dlProject/components/data_split.py
    deps:
      - src/dlProject/components/data_split.py
      - artifacts/data_feb16/data_transformation
      - config/config.yaml
    params:
      - data_split.test_size
    outs:
      - artifacts/data_feb16/data_split 

  # model_builder:
  #   cmd: python3 src/dlProject/components/model_builder.py
  #   deps:
  #     - src/dlProject/components/model_builder.py
  #     - config/config.yaml
  #   outs:
  #     - artifacts/data_feb16/model_builder    

  # model_trainer:  
  #   cmd: python3 src/dlProject/components/model_trainer.py
  #   deps:
  #     - src/dlProject/components/model_trainer.py
  #     - artifacts/data_feb16/data_split
  #     - config/config.yaml
  #     - params.yaml
  #   outs:
  #     - artifacts/data_feb16/model_trainer    

  # model_test:
  #   cmd: python3 src/dlProject/components/model_test.py
  #   deps:
  #     - src/dlProject/components/model_test.py
  #     - config/config.yaml
  #     - params.yaml
  #   outs:
  #     - artifacts/data_feb16/model_test