
stages:
  data_ingestion:
    cmd: python3 src/dlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/dlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - data_source/tr_ext_Solana_alldata_mapped_100per.parquet
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_ingestion

  data_transformation:
    cmd: python3 src/dlProject/pipeline/stage_02_data_transformation.py
    deps:
      - src/dlProject/pipeline/stage_02_data_transformation.py
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_ingestion
      - config/config.yaml
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_transformation  

  data_preprocessing:
    cmd: python3 src/dlProject/pipeline/stage_02a_data_preparation.py
    deps:
      - src/dlProject/pipeline/stage_02a_data_preparation.py
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_transformation
      - config/config.yaml
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_preparation

  data_split:
    cmd: python3 src/dlProject/pipeline/stage_03_data_split.py
    deps:
      - src/dlProject/pipeline/stage_03_data_split.py
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_preparation
      - config/config.yaml
    params:
      - data_split.test_size
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_split 

  # feature_selection:
  #   cmd: python3 src/dlProject/pipeline/stage_03a_feature_selection.py
  #   deps:
  #     - src/dlProject/pipeline/stage_03a_feature_selection.py
  #     - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_split
  #     - config/config.yaml
  #   outs:
  #     - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/feature_selection

  model_builder:
    cmd: python3 src/dlProject/pipeline/stage_04_model_build.py
    deps:
      - src/dlProject/pipeline/stage_04_model_build.py
      - config/config.yaml
    params: 
      - project.model_type
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/model_builder    

  model_trainer:  
    cmd: python3 src/dlProject/pipeline/stage_05_model_train.py
    deps:
      - src/dlProject/pipeline/stage_05_model_train.py
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/model_builder
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_split
      - src/dlProject/commons/create_tf_dataset.py
      # - artifacts/data_mar02/feature_selection
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/model_trainer    

  model_test:
    cmd: python3 src/dlProject/pipeline/stage_06_model_test.py
    deps:
      - src/dlProject/pipeline/stage_06_model_test.py
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/data_split
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/model_trainer
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/data_mar04a_ds_tcp_ssl_features_selected_lr0.0001_dr/model_test

