

stat_features_twc = ["pkt_fwd_count", 
    "pl_fwd_count",
    "pl_len_fwd_mean", 
    "pl_len_fwd_stdev",
    "pl_len_fwd_total", 
    "pl_len_fwd_min", 
    "pl_len_fwd_max",
    "pkt_len_fwd_mean", 
    "pkt_len_fwd_stdev", 
    "pkt_len_fwd_total",
    "pkt_len_fwd_min", 
    "pkt_len_fwd_max", 
    "iat_fwd_mean", 
    "iat_fwd_stdev",
    "iat_fwd_total", 
    "iat_fwd_min", 
    "iat_fwd_max", 
    "pkt_bwd_count",
    "pl_bwd_count", 
    "last_timestamp_bwd", 
    "pl_len_bwd_mean",
    "pl_len_bwd_stdev", 
    "pl_len_bwd_total", 
    "pl_len_bwd_min",
    "pl_len_bwd_max", 
    "pkt_len_bwd_mean", 
    "pkt_len_bwd_stdev",
    "pkt_len_bwd_total", 
    "pkt_len_bwd_min", 
    "pkt_len_bwd_max",
    "iat_bwd_mean", 
    "iat_bwd_stdev", 
    "iat_bwd_total", 
    "iat_bwd_min",
    "iat_bwd_max"
]

stat_features_twc_test = ["pl_len_fwd_min", "pl_len_fwd_mean", "pl_len_fwd_max", 
"pl_len_fwd_stdev", "pl_len_bwd_min", "pl_len_bwd_mean", 
"pl_len_bwd_max", "pl_len_bwd_stdev", "pkt_len_fwd_min", 
"pkt_len_fwd_mean", "pkt_len_fwd_max", "pkt_len_fwd_stdev", 
"pkt_len_bwd_min", "pkt_len_bwd_mean", "pkt_len_bwd_max", 
"pkt_len_bwd_stdev"] 

seq_packet_feature = ["splt_ps", "splt_piat", "splt_direction"]

stat_features_nfs = [
    'bidirectional_duration_ms', 'bidirectional_packets',
    'bidirectional_bytes', 'src2dst_duration_ms', 'src2dst_packets',
    'src2dst_bytes', 'dst2src_duration_ms', 'dst2src_packets',
    'dst2src_bytes', 'bidirectional_min_ps', 'bidirectional_mean_ps',
    'bidirectional_stddev_ps', 'bidirectional_max_ps', 'src2dst_min_ps',
    'src2dst_mean_ps', 'src2dst_stddev_ps', 'src2dst_max_ps',
    'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
    'dst2src_max_ps', 'bidirectional_min_piat_ms',
    'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
    'bidirectional_max_piat_ms', 'src2dst_min_piat_ms',
    'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
    'dst2src_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
    'dst2src_max_piat_ms', 'bidirectional_syn_packets',
    'bidirectional_cwr_packets', 'bidirectional_ece_packets',
    'bidirectional_urg_packets', 'bidirectional_ack_packets',
    'bidirectional_psh_packets', 'bidirectional_rst_packets',
    'bidirectional_fin_packets', 'src2dst_syn_packets',
    'src2dst_cwr_packets', 'src2dst_ece_packets', 'src2dst_urg_packets',
    'src2dst_ack_packets', 'src2dst_psh_packets', 'src2dst_rst_packets',
    'src2dst_fin_packets', 'dst2src_syn_packets', 'dst2src_cwr_packets',
    'dst2src_ece_packets', 'dst2src_urg_packets', 'dst2src_ack_packets',
    'dst2src_psh_packets', 'dst2src_rst_packets', 'dst2src_fin_packets'
]

target_column = "refined_app_label"

target_labels2 = ["Discord", "Telegram", "Microsoft Teams", "Whatsapp", "Facebook Messenger", "Signal"]

target_labels = ["Amazon",
            "Amazon Prime Music",
            "Amazon Prime Video",
            "Apple",
            "Apple Music",
            "BitTorrent",
            "Dailymotion",
            "Deezer",
            "Discord",
            "Dropbox",
            "Facebook Messenger",
            "Facebook TV",
            "Gmail",
            "Google",
            "Google Chat",
            "Google Docs",
            "Google Drive",
            "Google Earth",
            "Google Shop",
            "Google Translate",
            "Gotomeeting",
            "Instagram",
            "Line",
            "Meta",
            "Microsoft Teams",
            "Netflix",
            "SCP",
            "Signal",
            "Skype",
            "Slack",
            "Snapchat",
            "Spotify",
            "Tango",
            "Telegram",
            "Threema",
            "TikTok",
            "Twitch",
            "Viber",
            "Webex",
            "Wechat",
            "Whatsapp",
            "Youtube",
            "Zoom",
            "iMessage"]

data_sources_solana = ['2020a_Wireline_Ethernet', 
                    '2020c_Mobile_Wifi',
                    '2021a_Wireline_Ethernet', 
                    '2021c_Mobile_LTE',
                    '2022a_Wireline_Ethernet', 
                    '2023a_Wireline_Ethernet',
                    '2023c_Mobile_LTE', 
                    '2023e_MacOS_Wifi', 
                    '2024ag_Wireline_Ethernet',
                    '2024a_Wireline_Ethernet', 
                    '2024cg_Mobile_LTE', 
                    '2024c_Mobile_LTE',
                    '2024e_MacOS_Wifi'
                    ]

data_sources_homeoffice = ['Homeoffice2024ag_Wireline_Ethernet',
                    'Homeoffice2024a_Wireline_Ethernet', 
                    'Homeoffice2024c_Mobile_LTE',
                    'Homeoffice2024e_MacOS_WiFi', 
                    'Homeoffice2025cg_Mobile_LTE'
                    ]

data_sources_solanatest = ['Test2023a_Wireline_Ethernet', 
                    'Test2023c_Mobile_LTE',
                    'Test2023e_MacOS_Wifi', 
                    'Test2024ag_Wireline_Ethernet',
                    'Test2024a_Wireline_Ethernet', 
                    'Test2024cg_Mobile_LTE',
                    'Test2024c_Mobile_LTE', 
                    'Test2024e_MacOS_Wifi'
                    ]

stat_features_tr = ['duration_fwd',
'duration_bwd',
'dsMinPl_fwd',
'dsMinPl_bwd',
'dsMaxPl_fwd',
'dsMaxPl_bwd',
'dsMeanPl_fwd',
'dsMeanPl_bwd',
'dsLowQuartilePl_fwd',
'dsLowQuartilePl_bwd',
'dsMedianPl_fwd',
'dsMedianPl_bwd',
'dsUppQuartilePl_fwd',
'dsUppQuartilePl_bwd',
'dsIqdPl_fwd',
'dsIqdPl_bwd',
'dsModePl_fwd',
'dsModePl_bwd',
'dsRangePl_fwd',
'dsRangePl_bwd',
'dsStdPl_fwd',
'dsStdPl_bwd',
'dsRobStdPl_fwd',
'dsRobStdPl_bwd',
'dsSkewPl_fwd',
'dsSkewPl_bwd',
'dsExcPl_fwd',
'dsExcPl_bwd',
'dsMinIat_fwd',
'dsMinIat_bwd',
'dsMaxIat_fwd',
'dsMaxIat_bwd',
'dsMeanIat_fwd',
'dsMeanIat_bwd',
'dsLowQuartileIat_fwd',
'dsLowQuartileIat_bwd',
'dsMedianIat_fwd',
'dsMedianIat_bwd',
'dsUppQuartileIat_fwd',
'dsUppQuartileIat_bwd',
'dsIqdIat_fwd',
'dsIqdIat_bwd',
'dsModeIat_fwd',
'dsModeIat_bwd',
'dsRangeIat_fwd',
'dsRangeIat_bwd',
'dsStdIat_fwd',
'dsStdIat_bwd',
'dsRobStdIat_fwd',
'dsRobStdIat_bwd',
'dsSkewIat_fwd',
'dsSkewIat_bwd',
'dsExcIat_fwd',
'dsExcIat_bwd',
'PyldEntropy_fwd',
'PyldEntropy_bwd',
'PyldChRatio_fwd',
'PyldChRatio_bwd',
'PyldBinRatio_fwd',
'PyldBinRatio_bwd',
'pktsSnt',
'pktsRcvd',
'l7BytesSnt',
'l7BytesRcvd',
# ====================  
# 'dnsStat'  
# 'dnsAAAqF'  
# 'dnsQname'  
# 'dnsAname'  
# 'dnsAPname'  
# 'dns4Aaddress'  
# 'dnsHdrOPField_fwd'  
# 'dnsHdrOPField_bwd'  
# ====================  
'minL7PktSz_fwd',
'minL7PktSz_bwd',
'maxL7PktSz_fwd',
'maxL7PktSz_bwd',
'avgL7PktSz_fwd',
'avgL7PktSz_bwd',
'stdL7PktSz_fwd',
'stdL7PktSz_bwd',
'minIAT_fwd',
'minIAT_bwd',
'maxIAT_fwd',
'maxIAT_bwd',
'avgIAT_fwd',
'avgIAT_bwd',
'stdIAT_fwd',
'stdIAT_bwd',
'pktps_fwd',
'pktps_bwd',
'bytps_fwd',
'bytps_bwd',
'pktAsm_fwd',
'pktAsm_bwd',
'bytAsm_fwd',
'bytAsm_bwd',
'tcpFStat_fwd',
'tcpFStat_bwd',
'ipMindIPID_fwd',
'ipMindIPID_bwd',
'ipMaxdIPID_fwd',
'ipMaxdIPID_bwd',
'ipMinTTL_fwd',
'ipMinTTL_bwd',
'ipMaxTTL_fwd',
'ipMaxTTL_bwd',
'ipTTLChg_fwd',
'ipTTLChg_bwd',
'ipToS_fwd',
'ipToS_bwd',
'ipFlags',
'ipOptCnt',
# ==================  
'tcpISeqN_fwd',
'tcpISeqN_bwd',
'tcpPSeqCnt_fwd',
'tcpPSeqCnt_bwd',
'tcpSeqSntBytes_fwd',
'tcpSeqSntBytes_bwd',
'tcpSeqFaultCnt_fwd',
'tcpSeqFaultCnt_bwd',
'tcpPAckCnt_fwd',
'tcpPAckCnt_bwd',
'tcpFlwLssAckRcvdBytes_fwd',
'tcpFlwLssAckRcvdBytes_bwd',
'tcpAckFaultCnt_fwd',
'tcpAckFaultCnt_bwd',
'tcpBFlgtMx_fwd',
'tcpBFlgtMx_bwd',
'tcpInitWinSz_fwd',
'tcpInitWinSz_bwd',
'tcpAvgWinSz_fwd',
'tcpAvgWinSz_bwd',
'tcpMinWinSz_fwd',
'tcpMinWinSz_bwd',
'tcpMaxWinSz_fwd',
'tcpMaxWinSz_bwd',
'tcpWinSzDwnCnt_fwd',
'tcpWinSzDwnCnt_bwd',
'tcpWinSzUpCnt_fwd',
'tcpWinSzUpCnt_bwd',
'tcpWinSzChgDirCnt_fwd',
'tcpWinSzChgDirCnt_bwd',
'tcpWinSzThRt_fwd',
'tcpWinSzThRt_bwd',
'tcpWS_fwd',
'tcpWS_bwd',
'tcpFlags_fwd',
'tcpFlags_bwd',
'tcpAnomaly_fwd',
'tcpAnomaly_bwd',
# ====================  
'sslStat_fwd',
'sslStat_bwd',
'sslProto_fwd',
'sslProto_bwd',
'sslFlags_fwd',
'sslFlags_bwd',
'sslRecVer_fwd',
'sslRecVer_bwd',
'sslNumRecVer_fwd',
'sslNumRecVer_bwd',
'sslNumExt_fwd',
'sslNumExt_bwd',
'sslNumHandVer_fwd',
'sslNumHandVer_bwd',
'sslNumSuppVer_fwd',
'sslNumSuppVer_bwd',
'sslNumSigAlg_fwd',
'sslNumSigAlg_bwd',
'sslSigAlg_fwd',
'sslSigAlg_bwd',
'sslNumECPt_fwd',
'sslNumECPt_bwd',
'sslECPt_fwd',
'sslECPt_bwd',
'sslNumECFormats_fwd',
'sslNumECFormats_bwd',
'sslECFormats_fwd',
'sslECFormats_bwd'
]
