artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/solana_data_twc_extract/data_ingestion
  data_source_dir: data_source
  data_file_name: traffic_data_s.orc

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/solana_data_twc_extract/data_transformation
  data_source_dir: artifacts/solana_data_twc_extract/data_ingestion
  data_file_name: traffic_data_s.orc
  label_column: refined_app_label

data_split:
  root_dir: artifacts/solana_data_twc_extract/data_split
  data_source_dir: artifacts/solana_data_twc_extract/data_transformation
  data_file_name: traffic_data_s_transformed.csv
  params: {}
  # label_column: refined_app_label
  # test_size: 0.2

model_builder:
  root_dir: artifacts/solana_data_twc_extract/model_builder
  model_json: model.json
  model_plot: model.png
  params: {}

model_trainer:
  root_dir: artifacts/solana_data_twc_extract/model_trainer
  data_source_dir: artifacts/solana_data_twc_extract/data_split
  train_data_file_name: traffic_data_s_transformed_train.csv
  model_source_dir: artifacts/solana_data_twc_extract/model_builder
  model_file_name: model.json
  train_model_file_name: model.h5
  params: {}

model_test:
  root_dir: artifacts/solana_data_twc_extract/model_test
  data_source_dir: artifacts/solana_data_twc_extract/data_split
  test_data_file_name: traffic_data_s_transformed_test.csv
  model_dir: artifacts/solana_data_twc_extract/model_trainer    
  model_file_name: model.h5
  params: {}



