artifacts_root: artifacts
experiment_name: data_feb16

data_ingestion:
  root_dir: artifacts/data_mar01/data_ingestion
  data_source_dir: data_source
  data_file_name: tr_ext_Solana_alldata_mapped_100per.parquet
  
data_transformation:
  root_dir: artifacts/data_mar01/data_transformation
  data_source_dir: artifacts/data_mar01/data_ingestion
  data_file_name: tr_ext_Solana_alldata_mapped_100per.parquet
  label_column: refined_app_label

data_preprocessing:
  root_dir: artifacts/data_mar01/data_preparation
  data_source_dir: artifacts/data_mar01/data_transformation
  data_file_name: tr_ext_Solana_alldata_mapped_100per_transformed.csv

data_split:
  root_dir: artifacts/data_mar01/data_split
  data_source_dir: artifacts/data_mar01/data_preparation
  data_file_name: data_sources_solana.csv
  params: {}

feature_selection:
  root_dir: artifacts/data_mar01/feature_selection  
  data_source_dir: artifacts/data_mar01/data_split
  train_data_file_name: data_sources_solana_train.csv
  test_data_file_name: data_sources_solana_test.csv
  params: {}

model_builder:
  root_dir: artifacts/data_mar01/model_builder
  model_json: model.json
  model_plot: model.png
  params: {}

model_trainer:
  root_dir: artifacts/data_mar01/model_trainer
  data_source_dir: artifacts/data_mar01/data_split
  train_data_file_name: data_sources_solana_train.csv
  model_source_dir: artifacts/data_mar01/model_builder
  model_file_name: model.json
  train_model_file_name: model.h5
  params: {}

model_test:
  root_dir: artifacts/data_mar01/model_test
  data_source_dir: artifacts/data_mar01/data_split
  test_data_file_name: data_sources_solana_test.csv
  model_dir: artifacts/data_mar01/model_trainer    
  model_file_name: model.h5
  params: {}



